apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: phpbb
  namespace: argocd
spec:
  project: default

  source:
    repoURL: ssh://git@git.amir.project.com:222/tespkg/tes_manifests.git
    targetRevision: HEAD
    path: phpbb
  destination: 
    server: https://kubernetes.default.svc
    namespace: bookinfo

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true