---
- name: Install Docker CE on CentOS 7
  hosts: servers
  become: yes

  tasks:
    - name: Install required packages
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add Docker CE repository
      yum_repository:
        name: docker-ce
        description: Docker CE Repository
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg
        enabled: yes

    - name: Install Docker CE
      yum:
        name: docker-ce
        state: latest

    - name: Ensure Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: yes
