---
- name: Stop and disable firewall
  hosts: servers
  become: yes
  gather_facts: yes

  tasks:

    - name: Check if system is Ubuntu or CentOS
      set_fact:
        is_ubuntu: "{{ ansible_os_family == 'Debian' }}"
        is_centos: "{{ ansible_os_family == 'RedHat' }}"

    - name: Stop and disable firewall on Ubuntu
      service:
        name: ufw
        state: stopped
        enabled: no
      when: is_ubuntu

    - name: Stop and disable firewall on CentOS
      service:
        name: firewalld
        state: stopped
        enabled: no
      when: is_centos