---
- name: Install Python 3.10 and pip 21 on CentOS 7
  hosts: master1
  become: yes

  tasks:
    - name: Install EPEL repository
      yum:
        name: epel-release
        state: present

    - name: Install Python 3.10 dependencies
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - gcc
        - openssl-devel
        - bzip2-devel
        - libffi-devel
        - wget
        - make
        - zlib-devel
        - tk-devel
        - libuuid-devel
        - gdbm-devel
        - readline-devel
        - sqlite-devel
        - ncurses-devel
        - xz-devel

    - name: Download Python 3.10
      get_url:
        url: "https://www.python.org/ftp/python/3.10.0/Python-3.10.0.tgz"
        dest: /tmp/Python-3.10.0.tgz

    - name: Extract Python 3.10
      ansible.builtin.unarchive:
        src: /tmp/Python-3.10.0.tgz
        dest: /tmp
        remote_src: yes

    - name: Configure and Install Python 3.10
      ansible.builtin.shell: |
        cd /tmp/Python-3.10.0
        ./configure --prefix=/usr/local --enable-optimizations
        make altinstall
      args:
        executable: /bin/bash

    - name: Install pip for Python 3.10
      ansible.builtin.shell: |
        curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        python3.10 get-pip.py
      args:
        chdir: /tmp

    - name: Upgrade pip to version 21
      pip:
        name: pip
        executable: /usr/local/bin/python3.10
        extra_args: "--upgrade pip==21.*"
        state: present

    - name: Verify pip version
      command: /usr/local/bin/python3.10 -m pip --version
      register: pip_version
      changed_when: false

    - name: Print pip version
      ansible.builtin.debug:
        msg: "Installed pip version is {{ pip_version.stdout }}"

  handlers:
    - name: Restart Services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: restarted
      loop:
        - httpd
        - nginx
