---
- name: Run Rancher container
  hosts: servers
  become: yes

  tasks:
    - name: FIX PIP
      shell: |
        curl "https://bootstrap.pypa.io/pip/2.7/get-pip.py" -o "get-pip.py"
        python get-pip.py
        pip install docker-py        
  
    - name: Pull a Docker Image
      docker_image: 
         name: rancher/rancher
         tag: v2.6.3
         source: pull
      register: z
    - name: Checking Pull Status
      debug: 
        var: z
 
    - name: Rancher directory
      file:
        path: "/rancher"
        state: directory
        
    - name: Rancher cert directory
      file:
        path: "/rancher/certs"
        state: directory        
 
    - name: Copying certs
      copy: 
        src: "./certs"
        dest: "/rancher"
 
    - name: Launching RANCHER CONTAINER
      when: z.failed == false
      docker_container:
        name: rancher
        image: rancher/rancher:v2.6.3
        state: started
        env:
          CATTLE_BOOTSTRAP_PASSWORD: "admin@pak"
        exposed_ports:
          - "80"
          - "443"
        ports:
          - "80:80"
          - "443:443"
        volumes: 
          - /rancher/certs:/etc/rancher/ssl
          - /rancher/opt:/var/lib/rancher
        restart_policy: always
        privileged: yes
# ********************************************Enable if passwword variable is not set   
#    - name: Get last 10 lines of log file
#      ansible.builtin.shell:
#        cmd: docker logs  rancher  2>&1 | grep "Bootstrap Password:"
#      register: last_10_lines
#
#    - debug:
#        var: last_10_lines.stdout_lines