---
- name: Deploy Rancher
  hosts: servers
#  vars:
#    ansible_python_interpreter: /usr/bin/python3.6
  become: yes
  gather_facts: yes

  tasks:
    - name: Deploy rancher
      community.docker.docker_container:
        name: rancher
        image: "rancher/rancher:v2.6.3"
        ports:
          - "443:443"
          - "80:80"
        volumes:
          - /rancher/certs:/etc/rancher/ssl
          - /rancher/opt:/var/lib/rancher
        restart_policy: unless-stopped