---
- name: Launch rancher container
  hosts: servers
  become: yes  # If Docker requires sudo access

  tasks:
    - name: Pull a Docker Image
      docker_image: 
         name: rancher/rancher
         tag: v2.6.3
         source: pull
      register: z
    - name: Checking Pull Status
      debug: 
        var: z
 
    - name: Rancher directory-1
      file:
        path: "/rancher"
        state: directory
        
    - name: Rancher directory-2
      file:
        path: "/rancher/certs"
        state: directory        
 
    - name: Copying certs
      copy: 
        src: "./certs"
        dest: "/rancher"
 
    - name: Launching RANCHER CONTAINER
      when: z.failed == false
      docker_container:
        name: rancher
        image: rancher/rancher:v2.6.3
        state: started
        exposed_ports:
          - "80"
          - "443"
        ports:
          - "80:80"
          - "443:443"
        volumes: 
          - /rancher/certs:/etc/rancher/ssl
          - /rancher/opt:/var/lib/rancher
        restart_policy: always
        privileged: yes