---
- name: Launch Nginx container
  hosts: servers
  become: yes  # If Docker requires sudo access

  tasks:
    - name: Pull Nginx Docker image
      docker_image:
        name: nginx:latest

    - name: Run Nginx container
      docker_container:
        name: my_nginx_container
        image: nginx:latest
        ports:
          - "80:80"  # Map container's port 80 to host's port 80
        volumes:
          - /root/nginx:/nginx  # Optional: Mount custom Nginx configuration
        restart_policy: always  # Restart container if it stops
