---
- name: Pre-Config
  hosts: servers
  become: yes
  vars:
    docker_ce_version: "20.10.24-3.el9"
    docker_ce_cli_version: "20.10.24-3.el9"
    containerd_io_version: "1.6.19-3.1.el9"  
  
  tasks:
  
    - name: Check if system is Ubuntu or CentOS
      set_fact:
        is_ubuntu: "{{ ansible_os_family == 'Debian' }}"
        is_centos: "{{ ansible_os_family == 'RedHat' }}"

    - name: Stop and disable firewall on Ubuntu
      service:
        name: ufw
        state: stopped
        enabled: no
      when: is_ubuntu

    - name: Stop and disable firewall on CentOS
      service:
        name: firewalld
        state: stopped
        enabled: no
      when: is_centos
      
      
    - name: firewall-disabled
      debug:
        msg: "============disable firewal Done============"
        
    - name: Disable SELinux
      selinux:
        state: disabled
      when: is_centos        
    - name: selinux-disabled   
      debug:
        msg: "============disable selinux Done============"

    - name: disableSwap
      shell: |
        swapoff -a
        sed -i 's/\(.*swap.*\)/# \1/g' /etc/fstab
        sed -i -e 's/# #/#/g' /etc/fstab
        sed -i -e '/net.ipv4.ip_nonlocal_bind/d' /etc/sysctl.conf
        echo "net.ipv4.ip_nonlocal_bind = 1" | sudo tee -a /etc/sysctl.conf
        sed -i -e '/net.ipv4.ip_forward/d' /etc/sysctl.conf
        echo "net.ipv4.ip_forward = 1" | sudo tee -a /etc/sysctl.conf
        sed -i -e '/net.bridge.bridge-nf-call-ip6tables/d' /etc/sysctl.conf
        echo "net.bridge.bridge-nf-call-ip6tables = 1" | sudo tee -a /etc/sysctl.conf
        sed -i -e '/net.bridge.bridge-nf-call-iptables/d' /etc/sysctl.conf
        echo "net.bridge.bridge-nf-call-iptables = 1" | sudo tee -a /etc/sysctl.conf
        sed -i -e '/vm.swappiness/d' /etc/sysctl.conf
        echo "vm.swappiness=0" | sudo tee -a /etc/sysctl.conf
        modprobe br_netfilter
        sysctl -p
      when: is_centos  
        
    - name: disableSwap
      debug:
        msg: "============disableSwap Done============"
        
    - name: network fix
      shell: |
        sudo iptables -P FORWARD ACCEPT
        echo 'net.ipv4.ip_forward = 1' | sudo tee -a /etc/sysctl.d/50-docker-forward.conf
        for mod in ip_tables ip_vs_sh ip_vs ip_vs_rr ip_vs_wrr; do sudo modprobe $mod; echo $mod | sudo tee -a /etc/modules-load.d/iptables.conf; done
        sudo dnf -y install network-scripts
        sudo systemctl enable network
        sudo systemctl start network
        sudo mkdir /etc/kubernetes
        yum install -y yum-utils
        yum install -y iscsi-initiator-utils
        yum install -y nfs-utils
      when: is_centos

      
    - name: disableSwap
      debug:
        msg: "============network fix Done============"

    - name: TimeDate
      shell: |
        timedatectl set-timezone Asia/Karachi
    - name: TimeDate
      debug:
        msg: "============Time and Date set============"

    - name: Install required packages
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
      when: is_centos  


    - name: Install required packages
      yum:
        name: yum-utils
        state: present

    - name: Add Docker repository
      command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker CE specific version
      yum:
        name:
          - "docker-ce-{{ docker_ce_version }}"
          - "docker-ce-cli-{{ docker_ce_cli_version }}"
          - "containerd.io-{{ containerd_io_version }}"
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add user to Docker group
      user:
        name: your_username
        groups: docker
        append: yes
      become: true
      become_user: root
      # Replace 'your_username' with the actual username

  handlers:
    - name: Restart Docker
      systemd:
        name: docker
        state: restarted


    - name: docker version lock
      shell: |
        yum -y install yum-versionlock
        yum versionlock add docker-ce
        yum versionlock list docker-ce
      when: is_centos  
    - name: script
      debug:
        msg: "==========docker version lock succeded==========="


    - name: docker compose
      shell: |
        curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose  
    - name: script
      debug:
        msg: "==========docker compose succeded==========="
        
#with Ubuntu

    - name: install prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates 
          - curl 
          - gnupg-agent
          - software-properties-common
        update_cache: yes
      when: is_ubuntu
  
    - name: add apt-key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
      when: is_ubuntu    
  
    - name: add docker repo
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
      when: is_ubuntu    
  
    - name: install docker 
      apt:
        name: 
          - docker-ce=5:20.10.5~3-0~ubuntu-focal
          - docker-ce-cli=5:20.10.5~3-0~ubuntu-focal
          - containerd.io
        update_cache: yes
      when: is_ubuntu

    - name: services
      shell: |
        swapoff -a
        sudo sed -i.bak '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
        apt-get install open-iscsi -y
      when: is_ubuntu    
      
    - name: Copy Root CA certificate to the target machine
      copy:
        src: ../certs/cacerts.crt
        dest: /etc/pki/ca-trust/source/anchors/
      when: is_centos        

    - name: Update the trusted certificates store
      command: update-ca-trust      
      when: is_centos      