---
- name: Run Rancher container
  hosts: servers
  become: yes

  tasks:
    - name: FIX PIP
      shell: |
        curl "https://bootstrap.pypa.io/pip/2.7/get-pip.py" -o "get-pip.py"
        python get-pip.py
        pip install docker-py        
  
    - name: Pull Rancher container image
      docker_image:
        name: rancher/rancher:v2.6.3
        source: pull

    - name: Run Rancher container
      docker_container:
        name: rancher
        image: rancher/rancher:v2.6.3
        ports:
          - "80:80"
          - "443:443"
        restart_policy: always
